# 単純パーセプトロンで論理ゲートを実現する

「物体・画像認識と時系列データ処理入門」p.148

In [1]:
import numpy as np

## 単純パーセプトロンで二値分類を行う

In [2]:
def create_matrix(x):
    '''
    データx1, x2にバイアスに対応するx0(=1)を加えた行列を作成
    ---
    Parameters:
      x(ndarray): x1, x2を格納した2階テンソル
    '''
    x0 = np.ones([x.shape[0], 1])  # バイアスに対応する1の項(x0)を生成
                                    # 形状は(4,1)の2階テンソル
    return np.hstack([x0, x])  # x0の(4,1)の2階テンソルにx1,x2の2階テンソルを
                                # 水平方向に連結して(4,3)の2階テンソルを返す

In [3]:
a0 = np.array([[10, 15, 20, 25, 30],
              [20, 30, 40, 50, 60]])
a = np.transpose(a0)
b = create_matrix(a)
print(b)

[[ 1. 10. 20.]
 [ 1. 15. 30.]
 [ 1. 20. 40.]
 [ 1. 25. 50.]
 [ 1. 30. 60.]]


In [4]:
def sigmoid(X, parameter):
    '''
    シグモイド関数
    ---
    Parameters:
      X(ndarray): x0, x1, x2を格納した2階テンソル
      parameter(ndarray): バイアス, w1, w2を格納した1階テンソル
    Returns:
      シグモイド関数適用後のX
    '''
    return 1 / (1 + np.exp(-np.dot(X, parameter)))

In [5]:
c = np.array([0.5, -0.8, 0.2])
d = sigmoid(b, c)
print(d)

[2.93122308e-02 4.07013772e-03 5.52778637e-04 7.48462275e-05
 1.01299910e-05]


In [6]:
def logistic_regression(X, t):
    '''
    二値分類を行う単純パーセプトロン
    ---
    Parameters:
        X(ndarray): x0, x1, x2を格納した2階テンソル
        t(ndarray): 正解ラベルが格納された1階テンソル
    '''
    LNR = 1e-1    # 学習率を0.1に設定
    loop = 50    # 学習回数
    count = 1    # 学習回数をカウントする変数
    parameter = np.random.rand(3)    # バイアス, w1, w2 を0-1の一様乱数で初期化
    for i in range(loop):    # 学習をloop回繰り返す
        # バイアス, w1, w2を勾配降下法で更新
        parameter = parameter - LNR * np.dot(
            sigmoid(X, parameter) - t, X)
        # 最初の1回と以降10回ごとにパラメータの値を出力
        if (count == 1 or count % 10 == 0):
            print('{}回: parameter = {}'.format(count, parameter))
        count += 1    # カウンターの変数の値を1増やす
    return parameter    # 学習後のバイアス, w1, w2を返す

## ANDゲートの学習を行う

In [7]:
# ANDゲート
# x1, x2の4セットを行列x(ndarray)に代入
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに記入
t = np.array([0, 0, 0, 1])
# xにバイアス対応の1の値を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.74512074 0.71130683 0.7251647 ]
10回: parameter = [-0.59768442  0.39204236  0.40337193]
20回: parameter = [-1.16324735  0.50939691  0.51831387]
30回: parameter = [-1.49994476  0.71184953  0.71898677]
40回: parameter = [-1.77253091  0.91039724  0.91615641]
50回: parameter = [-2.01518281  1.0921187   1.09679287]


## 学習した重み・バイアスを使ってANDゲートの出力を表示してみる

In [8]:
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
    parameter # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

C:\Users\nicjp\AppData\Local\Temp\ipykernel_7216\2725429307.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ) >= 0.5).astype(np.int)


array([0, 0, 0, 1])

## NANDゲートの学習を行う

In [9]:
# NANDゲート
# x1, x2の4セットを行列x(ndarray)に代入
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに記入
t = np.array([1, 1, 1, 0])
# xにバイアス対応の1の値を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.4123047  0.00980893 0.1942579 ]
10回: parameter = [ 0.80155684 -0.22623395 -0.07658363]
20回: parameter = [ 1.1462155  -0.47827709 -0.35878747]
30回: parameter = [ 1.44583373 -0.70371544 -0.60780019]
40回: parameter = [ 1.71521361 -0.90415917 -0.82678248]
50回: parameter = [ 1.96083556 -1.08401059 -1.02127272]


## 学習した重み・バイアスを使ってNANDゲートの出力を表示してみる

In [10]:
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
    parameter # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

C:\Users\nicjp\AppData\Local\Temp\ipykernel_7216\2725429307.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ) >= 0.5).astype(np.int)


array([1, 1, 1, 0])

## ORゲートの学習を行う

In [11]:
# ORゲート
# x1, x2の4セットを行列x(ndarray)に代入
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
# 正解ラベルをtに記入
t = np.array([0, 1, 1, 1])
# xにバイアス対応の1の値を追加した2階テンソルを作成
X = create_matrix(x)
# バイアス、重みの値を学習する
parameter = logistic_regression(X, t)

1回: parameter = [0.404106   0.33786975 0.74290103]
10回: parameter = [0.42485874 0.71451157 1.05729365]
20回: parameter = [0.31266154 1.02193872 1.31397366]
30回: parameter = [0.16751731 1.27899164 1.5308787 ]
40回: parameter = [0.02167057 1.50674806 1.72561495]
50回: parameter = [-0.11518967  1.71372007  1.90497334]


## 学習した重み・バイアスを使ってORゲートの出力を表示してみる

In [12]:
# sigmoid()の戻り値が0.5以上であれば1、そうでなければ0を返す
(sigmoid(create_matrix(np.array([[0, 0], [0, 1], [1, 0], [1, 1]])),
    parameter # 学習後のバイアスと重み
) >= 0.5).astype(np.int)

C:\Users\nicjp\AppData\Local\Temp\ipykernel_7216\2725429307.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ) >= 0.5).astype(np.int)


array([0, 1, 1, 1])